verbose: 0
debug: false
elogger: false # Whether to activate email logging
host_sglang: false  # Whether to host the sglang server through code for the agents
local_sglang: false # If true, will save the model in the local directory (get around the bug: https://github.com/vllm-project/vllm/issues/2675)
sim_host: localhost  # The host for the environment simulator's SGLang server (the env must be on the same machine)
sim_port: 40042  # The port number for the environment simulator's SGLang server (the env must be on the same machine)
iter: 0
mode: consolidate_online # online, consolidate_online
logdir: data/guess_my_city/eval
rollout_data_dir: data/guess_my_city/eval/baseline/gpt4o
offline_data_dir: data/guess_my_city/sft/
data_types:
  - val
online:
  rollout_per_task_range_min: 0  # Inclusive
  rollout_per_task_range_max: 10  # Non-inclusive
  batch_size: 32
  num_alt_responses: 5
consolidate_online:
  main_table_notes: null
  table_notes: 'placeholder'
  rollout_per_task_dict:
    train: 1
    val: 3
    test: 3
  use_existing_table: false
  overwrite_existing_entry: true
agents:
  # - type: gpt4o_expert
  #   log_name: gpt4o
  # - type: sglang_server
  #   log_name: 3B
  #   model_id: meta-llama/Llama-3.2-3B-Instruct
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # ##########################################################################################
  # #
  # # Iteration 0: Train a initial SFT model via full finetuning
  # # 
  # ##########################################################################################
  # ######################## pi0
  # - type: sglang_server
  #   log_name: pi0-21pct
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250506_225348_iter0_pi0_vanilla_epochs=3/checkpoint-14
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # - type: sglang_server
  #   log_name: pi0-41pct  # pi0 Best Val Model
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250506_225348_iter0_pi0_vanilla_epochs=3/checkpoint-28
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # - type: sglang_server
  #   log_name: pi0-62pct
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250506_225348_iter0_pi0_vanilla_epochs=3/checkpoint-42
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # - type: sglang_server
  #   log_name: pi0-82pct
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250506_225348_iter0_pi0_vanilla_epochs=3/checkpoint-56
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # - type: sglang_server
  #   log_name: pi0
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250506_225348_iter0_pi0_vanilla_epochs=3/checkpoint-66
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  ##########################################################################################
  #
  # Iteration 1: PRM + RL
  # 
  ##########################################################################################
  # pi0: pi0-41pct
  - type: best_of_n
    log_name: BoN_pi0_Q0-20pct-lr=5e-6
    num_generations: 15 # Best of N (The critic will pick the best out of N responses)
    generator:
      type: sglang_server
      model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250506_225348_iter0_pi0_vanilla_epochs=3/checkpoint-28
      prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
      server_url: http://localhost:TODO/
      temperature: 0.7
      batch_limit: 32
      dist_url_port: null
    critic:
      type: sglang_server
      model_id: /share/portal/hw575/agent_prm/save/guess_my_city/rm/250508_163537_iter1_pi0-82pct_peft=false/model/checkpoint-250
      prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
      server_url: http://localhost:TODO/
      temperature: 0.3
      batch_limit: 16
      dist_url_port: null
    verbose: 3
  - type: best_of_n
    log_name: BoN_pi0_Q0-40pct-lr=5e-6
    num_generations: 15 # Best of N (The critic will pick the best out of N responses)
    generator:
      type: sglang_server
      model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250506_225348_iter0_pi0_vanilla_epochs=3/checkpoint-28
      prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
      server_url: http://localhost:TODO/
      temperature: 0.7
      batch_limit: 32
      dist_url_port: null
    critic:
      type: sglang_server
      model_id: /share/portal/hw575/agent_prm/save/guess_my_city/rm/250508_163537_iter1_pi0-82pct_peft=false/model/checkpoint-500
      prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
      server_url: http://localhost:TODO/
      temperature: 0.3
      batch_limit: 16
      dist_url_port: null
    verbose: 3
  - type: best_of_n
    log_name: BoN_pi0_Q0-60pct-lr=5e-6  # Vanilla PRM + RL Best val model
    num_generations: 15 # Best of N (The critic will pick the best out of N responses)
    generator:
      type: sglang_server
      model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250506_225348_iter0_pi0_vanilla_epochs=3/checkpoint-28
      prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
      server_url: http://localhost:TODO/
      temperature: 0.7
      batch_limit: 32
      dist_url_port: null
    critic:
      type: sglang_server
      model_id: /share/portal/hw575/agent_prm/save/guess_my_city/rm/250508_163537_iter1_pi0-82pct_peft=false/model/checkpoint-750
      prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
      server_url: http://localhost:TODO/
      temperature: 0.3
      batch_limit: 16
      dist_url_port: null
    verbose: 3
  - type: best_of_n
    log_name: BoN_pi0_Q0-80pct-lr=5e-6
    num_generations: 15 # Best of N (The critic will pick the best out of N responses)
    generator:
      type: sglang_server
      model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250506_225348_iter0_pi0_vanilla_epochs=3/checkpoint-28
      prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
      server_url: http://localhost:TODO/
      temperature: 0.7
      batch_limit: 32
      dist_url_port: null
    critic:
      type: sglang_server
      model_id: /share/portal/hw575/agent_prm/save/guess_my_city/rm/250508_163537_iter1_pi0-82pct_peft=false/model/checkpoint-1000
      prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
      server_url: http://localhost:TODO/
      temperature: 0.3
      batch_limit: 32
      dist_url_port: null
    verbose: 3
  - type: best_of_n
    log_name: BoN_pi0_Q0-lr=5e-6
    num_generations: 15 # Best of N (The critic will pick the best out of N responses)
    generator:
      type: sglang_server
      model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250506_225348_iter0_pi0_vanilla_epochs=3/checkpoint-28
      prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
      server_url: http://localhost:TODO/
      temperature: 0.7
      batch_limit: 32
      dist_url_port: null
    critic:
      type: sglang_server
      model_id: /share/portal/hw575/agent_prm/save/guess_my_city/rm/250508_163537_iter1_pi0-82pct_peft=false/model/checkpoint-1250
      prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
      server_url: http://localhost:TODO/
      temperature: 0.3
      batch_limit: 16
      dist_url_port: null
    verbose: 3
  ##########################################################################################
  #
  #       Multi-STaR
  # 
  ##########################################################################################
  ######################## pi1
  # - type: sglang_server
  #   log_name: pi1-21pct_multi-star
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250507_114222_iter1_multi-star_10k_pi1_multi-star_from-base_10k-data_lr=3e-6_epochs=1/checkpoint-16
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # - type: sglang_server
  #   log_name: pi1-41pct_multi-star
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250507_114222_iter1_multi-star_10k_pi1_multi-star_from-base_10k-data_lr=3e-6_epochs=1/checkpoint-32
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # - type: sglang_server
  #   log_name: pi1-62pct_multi-star
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250507_114222_iter1_multi-star_10k_pi1_multi-star_from-base_10k-data_lr=3e-6_epochs=1/checkpoint-48
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # - type: sglang_server
  #   log_name: pi1-82pct_multi-star  # Multi-STaR pi1 Best val model
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250507_114222_iter1_multi-star_10k_pi1_multi-star_from-base_10k-data_lr=3e-6_epochs=1/checkpoint-64
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # - type: sglang_server
  #   log_name: pi1_multi-star
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250507_114222_iter1_multi-star_10k_pi1_multi-star_from-base_10k-data_lr=3e-6_epochs=1/checkpoint-78
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  ######################## pi1
  # - type: sglang_server
  #   log_name: pi2-21pct_multi-star
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250507_173005_iter2_multi-star_10k_mix-50pct-past_pi2_multi-star_from-base_10k-data_50pct-past_lr=3e-6_epochs=1/checkpoint-16
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # - type: sglang_server
  #   log_name: pi2-41pct_multi-star
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250507_173005_iter2_multi-star_10k_mix-50pct-past_pi2_multi-star_from-base_10k-data_50pct-past_lr=3e-6_epochs=1/checkpoint-32
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # - type: sglang_server
  #   log_name: pi2-62pct_multi-star
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250507_173005_iter2_multi-star_10k_mix-50pct-past_pi2_multi-star_from-base_10k-data_50pct-past_lr=3e-6_epochs=1/checkpoint-48
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # - type: sglang_server
  #   log_name: pi2-82pct_multi-star
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250507_173005_iter2_multi-star_10k_mix-50pct-past_pi2_multi-star_from-base_10k-data_50pct-past_lr=3e-6_epochs=1/checkpoint-64
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3
  # - type: sglang_server
  #   log_name: pi2_multi-star
  #   model_id: /share/portal/hw575/agent_prm/save/guess_my_city/sft/250507_173005_iter2_multi-star_10k_mix-50pct-past_pi2_multi-star_from-base_10k-data_50pct-past_lr=3e-6_epochs=1/checkpoint-78
  #   prompt_template_file: prompts/guess_my_city/guess_my_city_template.j2
  #   server_url: http://localhost:TODO/
  #   dist_url_port: null
  #   temperature: 0.3
  #   batch_limit: 32
  #   verbose: 3


defaults:
  - _self_

hydra:
  run:
    dir: ${logdir}/iter${iter}/_hydra/${mode}/${now:%Y-%m-%d-%H%M%S%f}