domain: twenty_questions # alfworld, twenty_questions
rolloutdirs: 
  - /share/portal/hw575/agent_prm/data/twenty_questions/eval/iter0/3B-PSFT-all-data-3epoches_250224_225421_iter0-all_meta-llama-Llama-3.2-3B-Instruct_peft=true_epoch3+all/
iter: 1

# Either one is used
train_split: null
split_name: null

cpu_count: null
max_files_per_dir: null 
outputdir: data/${domain}/prm/iter${iter}
gamma: 0.95
seed: 42

defaults:
  - _self_

hydra:
  run:
    dir: ${outputdir}/hydra/${now:%Y-%m-%d-%H%M%S%f}
    