domain: none # alfworld, twenty_questions, car_dealer
rolloutdirs: 
  - REDACTED

# For Car-Dealer
# RUN python scripts/dataproc/tools/analyze_rollout_dataset.py
reward_min: -1.2448979591836735
reward_max: 1.8588387096774193

output_folder: null # So that we don't accidentally overwrite the existing data

# Either one is used
train_split: null
split_name: null

balance_data: true # Whether to enforce that 50% of data has Q-estimate >= 0.5 and 50% has Q-estimate < 0.5

cpu_count: null
max_files_per_dir: null 
max_rollout_per_task_per_dir_list: null

force_not_hindsight: false

hindsight:
  # Range for car dealer
  # onpolicy_idx_range: # The start and end of the on-policy rollouts
  #   - 0
  #   - 4
  #   - 30
  #   - 34
  #   - 60
  #   - 90
  # offpolicy_idx_range: 
  #   - 4
  #   - 20
  #   - 34
  #   - 50
  # Range for Guess My City
  # onpolicy_idx_range: # The start and end of the on-policy rollouts
  #   - 0
  #   - 4
  #   - 20
  #   - 24
  #   - 40
  #   - 70
  # offpolicy_idx_range: 
  #   - 4
  #   - 12
  #   - 24
  #   - 32
  # Range for 20 questions
  onpolicy_idx_range: # The start and end of the on-policy rollouts
    - 0
    - 4
    - 20
    - 24
    - 40
    - 44
    - 60
    - 64
    - 80
    - 84
    - 100
    - 104
  offpolicy_idx_range: 
    - 4
    - 12
    - 24
    - 32
  onpolicy_pct_for_success: null # Within the successful on-policy rollouts, only X pct of files are from on-policy rollouts
  num_failed_expert_rollouts_to_include: 0 # Only used in hindsight cases. Include X number of failed expert rollouts
  track_offpolicy: true # Whether to track the off-policy rollouts
  track_summary: false # Whether to track the summary as part of the states

outputdir: data/${domain}/prm/${output_folder}
gamma: 0.95
seed: 42

defaults:
  - _self_

hydra:
  run:
    dir: ${outputdir}/hydra/${now:%Y-%m-%d-%H%M%S%f}
    