# For each server, you need to specify the following: 
# - model_id
# - server_url
# - tp
# - dist_url_port
# - gpu_id (Optional, if you are running multiple servers on the same interactive session, specify which GPU to use)

server_configs:
  - model_id: /share/portal/hw575/agent_prm/save/online_dpo/250312_091827_iter1_-share-portal-hw575-agent_prm-save-sft-250307_212417_iter0-all_meta-llama-Llama-3.2-3B-Instruct_peft=false_epoch3+all-checkpoint-120_pen=-10_Q0-80pct-lr=5e-6/checkpoint-75
    server_url: http://localhost:30000/
    tp: 1
    dist_url_port: 29500
    gpu_id: 1
  - model_id: /share/portal/hw575/agent_prm/save/rm/250311_155325_iter1_-share-portal-hw575-agent_prm-save-sft-250307_212417_iter0-all_meta-llama-Llama-3.2-3B-Instruct_peft=false_epoch3+all-checkpoint-120_peft=false_lr=5e-6/model/checkpoint-1000
    server_url: http://localhost:30001/
    tp: 1
    dist_url_port: 29501
    gpu_id: 0

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .